import { Exercise } from '../types';

export const PREDEFINED_EXERCISES: Exercise[] = [
  // Chest (20)
  { id: 'ex-1', name: 'Bench Press', bodyPart: 'Chest', category: 'Barbell' },
  { id: 'ex-11', name: 'Dumbbell Fly', bodyPart: 'Chest', category: 'Dumbbell' },
  { id: 'ex-12', name: 'Incline Dumbbell Press', bodyPart: 'Chest', category: 'Dumbbell' },
  { id: 'ex-21', name: 'Cable Crossover', bodyPart: 'Chest', category: 'Cable' },
  { id: 'ex-22', name: 'Decline Bench Press', bodyPart: 'Chest', category: 'Barbell' },
  { id: 'ex-23', name: 'Push-Up', bodyPart: 'Chest', category: 'Bodyweight' },
  { id: 'ex-24', name: 'Dips', bodyPart: 'Chest', category: 'Assisted Bodyweight' },
  { id: 'ex-25', name: 'Incline Bench Press', bodyPart: 'Chest', category: 'Barbell' },
  { id: 'ex-26', name: 'Pec Deck Fly', bodyPart: 'Chest', category: 'Machine' },
  { id: 'ex-27', name: 'Svend Press', bodyPart: 'Chest', category: 'Reps Only' },
  { id: 'ex-28', name: 'Landmine Press', bodyPart: 'Chest', category: 'Barbell' },
  { id: 'ex-29', name: 'Deficit Push-Up', bodyPart: 'Chest', category: 'Bodyweight' },
  { id: 'ex-30', name: 'Archer Push-Up', bodyPart: 'Chest', category: 'Bodyweight' },
  { id: 'ex-31', name: 'Machine Chest Press', bodyPart: 'Chest', category: 'Machine' },
  { id: 'ex-32', name: 'Low-to-High Cable Fly', bodyPart: 'Chest', category: 'Cable' },
  { id: 'ex-33', name: 'High-to-Low Cable Fly', bodyPart: 'Chest', category: 'Cable' },
  { id: 'ex-34', name: 'Plate Press', bodyPart: 'Chest', category: 'Reps Only' },
  { id: 'ex-35', name: 'Suspension Push-Up', bodyPart: 'Chest', category: 'Assisted Bodyweight' },
  { id: 'ex-36', name: 'Isometric Chest Squeeze', bodyPart: 'Chest', category: 'Bodyweight' },
  { id: 'ex-37', name: 'Speed Bench Press', bodyPart: 'Chest', category: 'Barbell' },
  
  // Back (22)
  { id: 'ex-5', name: 'Barbell Row', bodyPart: 'Back', category: 'Barbell' },
  { id: 'ex-10', name: 'Lat Pulldown', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-3', name: 'Deadlift', bodyPart: 'Back', category: 'Barbell' },
  { id: 'ex-6', name: 'Pull Up', bodyPart: 'Back', category: 'Assisted Bodyweight' },
  { id: 'ex-38', name: 'Seated Row', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-39', name: 'T-Bar Row', bodyPart: 'Back', category: 'Machine' },
  { id: 'ex-40', name: 'Single-Arm Dumbbell Row', bodyPart: 'Back', category: 'Dumbbell' },
  { id: 'ex-41', name: 'Face Pull', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-42', name: 'Inverted Row', bodyPart: 'Back', category: 'Bodyweight' },
  { id: 'ex-43', name: 'Rack Pull', bodyPart: 'Back', category: 'Barbell' },
  { id: 'ex-44', name: 'Straight-Arm Pulldown', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-45', name: 'Hyperextension', bodyPart: 'Back', category: 'Bodyweight' },
  { id: 'ex-46', name: 'Superman', bodyPart: 'Back', category: 'Bodyweight' },
  { id: 'ex-47', name: 'Renegade Row', bodyPart: 'Back', category: 'Dumbbell' },
  { id: 'ex-48', name: 'Meadows Row', bodyPart: 'Back', category: 'Barbell' },
  { id: 'ex-49', name: 'Cable Pull-Over', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-50', name: 'Chin-Up', bodyPart: 'Back', category: 'Assisted Bodyweight' },
  { id: 'ex-51', name: 'Shrugs', bodyPart: 'Back', category: 'Dumbbell' },
  { id: 'ex-52', name: 'Reverse Grip Pulldown', bodyPart: 'Back', category: 'Cable' },
  { id: 'ex-53', name: 'Band Pull-Apart', bodyPart: 'Back', category: 'Reps Only' },
  { id: 'ex-54', name: 'Farmer\'s Carry', bodyPart: 'Back', category: 'Dumbbell' },
  { id: 'ex-55', name: 'Good Morning', bodyPart: 'Back', category: 'Barbell' },

  // Shoulders (18)
  { id: 'ex-4', name: 'Overhead Press', bodyPart: 'Shoulders', category: 'Barbell' },
  { id: 'ex-56', name: 'Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-57', name: 'Front Raise', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-58', name: 'Rear Delt Fly', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-59', name: 'Upright Row', bodyPart: 'Shoulders', category: 'Barbell' },
  { id: 'ex-60', name: 'Arnold Press', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-61', name: 'Cable Lateral Raise', bodyPart: 'Shoulders', category: 'Cable' },
  { id: 'ex-62', name: 'Pike Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight' },
  { id: 'ex-63', name: 'Handstand Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight' },
  { id: 'ex-64', name: 'Egyptian Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-65', name: 'Y-Raise', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-66', name: 'Cuban Press', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-67', name: 'Machine Shoulder Press', bodyPart: 'Shoulders', category: 'Machine' },
  { id: 'ex-68', name: 'Behind-the-Neck Press', bodyPart: 'Shoulders', category: 'Barbell' },
  { id: 'ex-69', name: 'Plate Front Raise', bodyPart: 'Shoulders', category: 'Reps Only' },
  { id: 'ex-70', name: 'Band Shoulder Press', bodyPart: 'Shoulders', category: 'Reps Only' },
  { id: 'ex-71', name: 'Dumbbell Shrugs', bodyPart: 'Shoulders', category: 'Dumbbell' },
  { id: 'ex-72', name: 'Wall Slide', bodyPart: 'Shoulders', category: 'Bodyweight' },

  // Biceps (15)
  { id: 'ex-7', name: 'Barbell Curl', bodyPart: 'Biceps', category: 'Barbell' },
  { id: 'ex-13', name: 'Bicep Curl', bodyPart: 'Biceps', category: 'Dumbbell' },
  { id: 'ex-73', name: 'Hammer Curl', bodyPart: 'Biceps', category: 'Dumbbell' },
  { id: 'ex-74', name: 'Concentration Curl', bodyPart: 'Biceps', category: 'Dumbbell' },
  { id: 'ex-75', name: 'Preacher Curl', bodyPart: 'Biceps', category: 'Machine' },
  { id: 'ex-76', name: 'Cable Curl', bodyPart: 'Biceps', category: 'Cable' },
  { id: 'ex-77', name: 'Incline Dumbbell Curl', bodyPart: 'Biceps', category: 'Dumbbell' },
  { id: 'ex-78', name: '21s Curl', bodyPart: 'Biceps', category: 'Barbell' },
  { id: 'ex-79', name: 'Spider Curl', bodyPart: 'Biceps', category: 'Barbell' },
  { id: 'ex-80', name: 'Zottman Curl', bodyPart: 'Biceps', category: 'Dumbbell' },
  { id: 'ex-81', name: 'Bayesian Cable Curl', bodyPart: 'Biceps', category: 'Cable' },
  { id: 'ex-82', name: 'Isometric Bicep Hold', bodyPart: 'Biceps', category: 'Bodyweight' },
  { id: 'ex-83', name: 'Band Curl', bodyPart: 'Biceps', category: 'Reps Only' },
  { id: 'ex-84', name: 'Drag Curl', bodyPart: 'Biceps', category: 'Barbell' },

  // Triceps (16)
  { id: 'ex-8', name: 'Skull Crusher', bodyPart: 'Triceps', category: 'Barbell' },
  { id: 'ex-14', name: 'Tricep Extension', bodyPart: 'Triceps', category: 'Cable' },
  { id: 'ex-85', name: 'Tricep Pushdown', bodyPart: 'Triceps', category: 'Cable' },
  { id: 'ex-86', name: 'Overhead Tricep Extension', bodyPart: 'Triceps', category: 'Dumbbell' },
  { id: 'ex-87', name: 'Close-Grip Bench Press', bodyPart: 'Triceps', category: 'Barbell' },
  { id: 'ex-88', name: 'French Press', bodyPart: 'Triceps', category: 'Barbell' },
  { id: 'ex-89', name: 'Bench Dip', bodyPart: 'Triceps', category: 'Bodyweight' },
  { id: 'ex-90', name: 'Rope Pushdown', bodyPart: 'Triceps', category: 'Cable' },
  { id: 'ex-91', name: 'JM Press', bodyPart: 'Triceps', category: 'Barbell' },
  { id: 'ex-92', name: 'Kickback', bodyPart: 'Triceps', category: 'Dumbbell' },
  { id: 'ex-93', name: 'Reverse Grip Pushdown', bodyPart: 'Triceps', category: 'Cable' },
  { id: 'ex-94', name: 'Cross-Body Extension', bodyPart: 'Triceps', category: 'Dumbbell' },
  { id: 'ex-95', name: 'Band Pushdown', bodyPart: 'Triceps', category: 'Reps Only' },
  { id: 'ex-96', name: 'Partial Tricep Extension', bodyPart: 'Triceps', category: 'Cable' },
  { id: 'ex-97', name: 'Isometric Tricep Squeeze', bodyPart: 'Triceps', category: 'Bodyweight' },

  // Legs (25)
  { id: 'ex-16', name: 'Leg Curl', bodyPart: 'Legs', category: 'Machine' },
  { id: 'ex-17', name: 'Leg Extension', bodyPart: 'Legs', category: 'Machine' },
  { id: 'ex-9', name: 'Leg Press', bodyPart: 'Legs', category: 'Machine' },
  { id: 'ex-2', name: 'Squat', bodyPart: 'Legs', category: 'Barbell' },
  { id: 'ex-18', name: 'Calf Raise', bodyPart: 'Calves', category: 'Machine' },
  { id: 'ex-98', name: 'Romanian Deadlift', bodyPart: 'Legs', category: 'Barbell' },
  { id: 'ex-99', name: 'Walking Lunge', bodyPart: 'Legs', category: 'Dumbbell' },
  { id: 'ex-100', name: 'Bulgarian Split Squat', bodyPart: 'Legs', category: 'Dumbbell' },
  { id: 'ex-101', name: 'Front Squat', bodyPart: 'Legs', category: 'Barbell' },
  { id: 'ex-102', name: 'Hack Squat', bodyPart: 'Legs', category: 'Machine' },
  { id: 'ex-103', name: 'Step-Up', bodyPart: 'Legs', category: 'Dumbbell' },
  { id: 'ex-104', name: 'Glute Bridge', bodyPart: 'Legs', category: 'Bodyweight' },
  { id: 'ex-105', name: 'Seated Calf Raise', bodyPart: 'Calves', category: 'Machine' },
  { id: 'ex-106', name: 'Donkey Calf Raise', bodyPart: 'Calves', category: 'Machine' },
  { id: 'ex-107', name: 'Leg Press Calf Raise', bodyPart: 'Calves', category: 'Machine' },
  { id: 'ex-108', name: 'Sumo Squat', bodyPart: 'Legs', category: 'Dumbbell' },
  { id: 'ex-109', name: 'Goblet Squat', bodyPart: 'Legs', category: 'Dumbbell' },
  { id: 'ex-110', name: 'Pistol Squat', bodyPart: 'Legs', category: 'Bodyweight' },
  { id: 'ex-111', name: 'Wall Sit', bodyPart: 'Legs', category: 'Duration' },
  { id: 'ex-112', name: 'Sissy Squat', bodyPart: 'Legs', category: 'Bodyweight' },
  { id: 'ex-113', name: 'Jefferson Squat', bodyPart: 'Legs', category: 'Barbell' },
  { id: 'ex-114', name: 'Band Leg Curl', bodyPart: 'Legs', category: 'Reps Only' },
  { id: 'ex-115', name: 'Cycling (Stationary)', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-116', name: 'Box Jump', bodyPart: 'Legs', category: 'Bodyweight' },

  // Core (15)
  { id: 'ex-20', name: 'Crunches', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-15', name: 'Plank', bodyPart: 'Core', category: 'Duration' },
  { id: 'ex-117', name: 'Russian Twist', bodyPart: 'Core', category: 'Dumbbell' },
  { id: 'ex-118', name: 'Leg Raise', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-119', name: 'Woodchopper', bodyPart: 'Core', category: 'Cable' },
  { id: 'ex-120', name: 'Pallof Press', bodyPart: 'Core', category: 'Cable' },
  { id: 'ex-121', name: 'Bird Dog', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-122', name: 'Dead Bug', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-123', name: 'Cable Crunch', bodyPart: 'Core', category: 'Cable' },
  { id: 'ex-124', name: 'Ab Wheel Rollout', bodyPart: 'Core', category: 'Reps Only' },
  { id: 'ex-125', name: 'Flutter Kick', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-126', name: 'V-Up', bodyPart: 'Core', category: 'Bodyweight' },
  { id: 'ex-127', name: 'Side Bend', bodyPart: 'Core', category: 'Dumbbell' },
  { id: 'ex-128', name: 'Vacuum', bodyPart: 'Core', category: 'Bodyweight' },

  // Cardio & Full Body (11)
  { id: 'ex-19', name: 'Running', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-129', name: 'Jumping Jacks', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-130', name: 'Burpee', bodyPart: 'Full Body', category: 'Cardio' },
  { id: 'ex-131', name: 'Mountain Climber', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-132', name: 'Rowing (Machine)', bodyPart: 'Full Body', category: 'Cardio' },
  { id: 'ex-133', name: 'Battle Rope', bodyPart: 'Full Body', category: 'Cardio' },
  { id: 'ex-134', name: 'Kettlebell Swing', bodyPart: 'Full Body', category: 'Reps Only' },
  { id: 'ex-135', name: 'Jump Rope', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-136', name: 'Stair Climber', bodyPart: 'Cardio', category: 'Cardio' },
  { id: 'ex-137', name: 'Swimming', bodyPart: 'Full Body', category: 'Cardio' },
  { id: 'ex-138', name: 'Sun Salutation', bodyPart: 'Full Body', category: 'Duration' },

  // Forearms (from Zottman Curl and Reverse Grip Pushdown)
  { id: 'ex-139', name: 'Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell'},
  { id: 'ex-140', name: 'Reverse Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell'},

];
