
import { Exercise } from '../types';
import { MUSCLES } from './muscles';

export const PREDEFINED_EXERCISES: Exercise[] = [
  // Chest (20)
  { id: 'ex-1', name: 'Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-11', name: 'Dumbbell Fly', bodyPart: 'Chest', category: 'Dumbbell', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-12', name: 'Incline Dumbbell Press', bodyPart: 'Chest', category: 'Dumbbell', primaryMuscles: [MUSCLES.UPPER_CHEST, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-21', name: 'Cable Crossover', bodyPart: 'Chest', category: 'Cable', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.LOWER_CHEST], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-22', name: 'Decline Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: [MUSCLES.LOWER_CHEST, MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.FRONT_DELTS] },
  { id: 'ex-23', name: 'Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.ABS, MUSCLES.SERRATUS_ANTERIOR] },
  { id: 'ex-24', name: 'Dips', bodyPart: 'Chest', category: 'Assisted Bodyweight', primaryMuscles: [MUSCLES.LOWER_CHEST, MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-25', name: 'Incline Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: [MUSCLES.UPPER_CHEST, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-26', name: 'Pec Deck Fly', bodyPart: 'Chest', category: 'Machine', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-27', name: 'Svend Press', bodyPart: 'Chest', category: 'Reps Only', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-28', name: 'Landmine Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: [MUSCLES.UPPER_CHEST, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-29', name: 'Deficit Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.FRONT_DELTS] },
  { id: 'ex-30', name: 'Archer Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.ABS] },
  { id: 'ex-31', name: 'Machine Chest Press', bodyPart: 'Chest', category: 'Machine', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.FRONT_DELTS] },
  { id: 'ex-32', name: 'Low-to-High Cable Fly', bodyPart: 'Chest', category: 'Cable', primaryMuscles: [MUSCLES.UPPER_CHEST], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-33', name: 'High-to-Low Cable Fly', bodyPart: 'Chest', category: 'Cable', primaryMuscles: [MUSCLES.LOWER_CHEST], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-34', name: 'Plate Press', bodyPart: 'Chest', category: 'Reps Only', primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.TRICEPS] },
  { id: 'ex-35', name: 'Suspension Push-Up', bodyPart: 'Chest', category: 'Assisted Bodyweight', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.ABS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.FRONT_DELTS, MUSCLES.SERRATUS_ANTERIOR] },
  { id: 'ex-36', name: 'Isometric Chest Squeeze', bodyPart: 'Chest', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.PECTORALS], secondaryMuscles: [] },
  { id: 'ex-37', name: 'Speed Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: [MUSCLES.PECTORALS, MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  
  // Back (23)
  { id: 'ex-5', name: 'Barbell Row', bodyPart: 'Back', category: 'Barbell', primaryMuscles: [MUSCLES.LATS, MUSCLES.RHOMBOIDS, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.REAR_DELTS, MUSCLES.LOWER_BACK] },
  { id: 'ex-10', name: 'Lat Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.LATS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.TERES_MAJOR] },
  { id: 'ex-3', name: 'Deadlift', bodyPart: 'Back', category: 'Barbell', primaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.HAMSTRINGS, MUSCLES.GLUTES, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.LATS, MUSCLES.FOREARMS, MUSCLES.QUADS] },
  { id: 'ex-6', name: 'Pull Up', bodyPart: 'Back', category: 'Assisted Bodyweight', primaryMuscles: [MUSCLES.LATS, MUSCLES.TERES_MAJOR], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.RHOMBOIDS, MUSCLES.TRAPS] },
  { id: 'ex-38', name: 'Seated Row', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.LATS, MUSCLES.RHOMBOIDS, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.REAR_DELTS] },
  { id: 'ex-39', name: 'T-Bar Row', bodyPart: 'Back', category: 'Machine', primaryMuscles: [MUSCLES.LATS, MUSCLES.TRAPS, MUSCLES.RHOMBOIDS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.LOWER_BACK] },
  { id: 'ex-40', name: 'Single-Arm Dumbbell Row', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: [MUSCLES.LATS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.RHOMBOIDS] },
  { id: 'ex-41', name: 'Face Pull', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.REAR_DELTS, MUSCLES.ROTATOR_CUFF, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.RHOMBOIDS] },
  { id: 'ex-42', name: 'Inverted Row', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: [MUSCLES.LATS, MUSCLES.RHOMBOIDS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.REAR_DELTS, MUSCLES.ABS] },
  { id: 'ex-43', name: 'Rack Pull', bodyPart: 'Back', category: 'Barbell', primaryMuscles: [MUSCLES.TRAPS, MUSCLES.LOWER_BACK], secondaryMuscles: [MUSCLES.LATS, MUSCLES.GLUTES, MUSCLES.HAMSTRINGS] },
  { id: 'ex-44', name: 'Straight-Arm Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.LATS, MUSCLES.TERES_MAJOR], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-45', name: 'Hyperextension', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: [MUSCLES.LOWER_BACK], secondaryMuscles: [MUSCLES.GLUTES, MUSCLES.HAMSTRINGS] },
  { id: 'ex-46', name: 'Superman', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: [MUSCLES.LOWER_BACK], secondaryMuscles: [MUSCLES.GLUTES] },
  { id: 'ex-47', name: 'Renegade Row', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: [MUSCLES.LATS, MUSCLES.ABS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.FRONT_DELTS, MUSCLES.OBLIQUES] },
  { id: 'ex-48', name: 'Meadows Row', bodyPart: 'Back', category: 'Barbell', primaryMuscles: [MUSCLES.LATS, MUSCLES.RHOMBOIDS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.FOREARMS] },
  { id: 'ex-49', name: 'Cable Pull-Over', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.LATS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.SERRATUS_ANTERIOR] },
  { id: 'ex-50', name: 'Chin-Up', bodyPart: 'Back', category: 'Assisted Bodyweight', primaryMuscles: [MUSCLES.LATS, MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.RHOMBOIDS] },
  { id: 'ex-51', name: 'Shrugs', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: [MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-52', name: 'Reverse Grip Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: [MUSCLES.LATS, MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.RHOMBOIDS] },
  { id: 'ex-53', name: 'Band Pull-Apart', bodyPart: 'Back', category: 'Reps Only', primaryMuscles: [MUSCLES.REAR_DELTS, MUSCLES.RHOMBOIDS], secondaryMuscles: [MUSCLES.TRAPS] },
  { id: 'ex-54', name: 'Farmer\'s Carry', bodyPart: 'Back', category: 'Dumbbell', isTimed: true, primaryMuscles: [MUSCLES.TRAPS, MUSCLES.FOREARMS], secondaryMuscles: [MUSCLES.ABS, MUSCLES.OBLIQUES, MUSCLES.GLUTES] },
  { id: 'ex-55', name: 'Good Morning', bodyPart: 'Back', category: 'Barbell', primaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.HAMSTRINGS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.ABS] },
  { id: 'ex-148', name: 'Kettlebell High Pull', bodyPart: 'Back', category: 'Kettlebell', primaryMuscles: [MUSCLES.TRAPS, MUSCLES.REAR_DELTS], secondaryMuscles: [MUSCLES.LATS, MUSCLES.BICEPS] },

  // Shoulders (18)
  { id: 'ex-4', name: 'Overhead Press', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.SIDE_DELTS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.UPPER_CHEST] },
  { id: 'ex-56', name: 'Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.SIDE_DELTS], secondaryMuscles: [MUSCLES.TRAPS] },
  { id: 'ex-57', name: 'Front Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.FRONT_DELTS], secondaryMuscles: [] },
  { id: 'ex-58', name: 'Rear Delt Fly', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.REAR_DELTS], secondaryMuscles: [MUSCLES.RHOMBOIDS] },
  { id: 'ex-59', name: 'Upright Row', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: [MUSCLES.SIDE_DELTS, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.FRONT_DELTS] },
  { id: 'ex-60', name: 'Arnold Press', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.SIDE_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-61', name: 'Cable Lateral Raise', bodyPart: 'Shoulders', category: 'Cable', primaryMuscles: [MUSCLES.SIDE_DELTS], secondaryMuscles: [] },
  { id: 'ex-62', name: 'Pike Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: [MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.UPPER_CHEST] },
  { id: 'ex-63', name: 'Handstand Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.SIDE_DELTS] },
  { id: 'ex-64', name: 'Egyptian Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.SIDE_DELTS], secondaryMuscles: [] },
  { id: 'ex-65', name: 'Y-Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.SIDE_DELTS, MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.REAR_DELTS] },
  { id: 'ex-66', name: 'Cuban Press', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.ROTATOR_CUFF, MUSCLES.SIDE_DELTS], secondaryMuscles: [MUSCLES.TRAPS] },
  { id: 'ex-67', name: 'Machine Shoulder Press', bodyPart: 'Shoulders', category: 'Machine', primaryMuscles: [MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-68', name: 'Behind-the-Neck Press', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: [MUSCLES.SIDE_DELTS, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-69', name: 'Plate Front Raise', bodyPart: 'Shoulders', category: 'Reps Only', primaryMuscles: [MUSCLES.FRONT_DELTS], secondaryMuscles: [] },
  { id: 'ex-70', name: 'Band Shoulder Press', bodyPart: 'Shoulders', category: 'Reps Only', primaryMuscles: [MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.TRICEPS] },
  { id: 'ex-71', name: 'Dumbbell Shrugs', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: [MUSCLES.TRAPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-72', name: 'Wall Slide', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: [MUSCLES.ROTATOR_CUFF, MUSCLES.SERRATUS_ANTERIOR], secondaryMuscles: [MUSCLES.TRAPS] },

  // Biceps (14)
  { id: 'ex-7', name: 'Barbell Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-13', name: 'Bicep Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-73', name: 'Hammer Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.BRACHIALIS, MUSCLES.FOREARMS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.FOREARMS] },
  { id: 'ex-74', name: 'Concentration Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-75', name: 'Preacher Curl', bodyPart: 'Biceps', category: 'Machine', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-76', name: 'Cable Curl', bodyPart: 'Biceps', category: 'Cable', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-77', name: 'Incline Dumbbell Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-78', name: '21s Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-79', name: 'Spider Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-80', name: 'Zottman Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.BICEPS, MUSCLES.FOREARMS], secondaryMuscles: [MUSCLES.BRACHIALIS] },
  { id: 'ex-81', name: 'Bayesian Cable Curl', bodyPart: 'Biceps', category: 'Cable', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-82', name: 'Isometric Bicep Hold', bodyPart: 'Biceps', category: 'Bodyweight', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-83', name: 'Band Curl', bodyPart: 'Biceps', category: 'Reps Only', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [] },
  { id: 'ex-84', name: 'Drag Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: [MUSCLES.BICEPS], secondaryMuscles: [MUSCLES.REAR_DELTS] },

  // Triceps (15)
  { id: 'ex-8', name: 'Skull Crusher', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-14', name: 'Tricep Extension', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-85', name: 'Tricep Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-86', name: 'Overhead Tricep Extension', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-87', name: 'Close-Grip Bench Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.PECTORALS, MUSCLES.FRONT_DELTS] },
  { id: 'ex-88', name: 'French Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-89', name: 'Bench Dip', bodyPart: 'Triceps', category: 'Bodyweight', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.PECTORALS] },
  { id: 'ex-90', name: 'Rope Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-91', name: 'JM Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.PECTORALS] },
  { id: 'ex-92', name: 'Kickback', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-93', name: 'Reverse Grip Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [MUSCLES.FOREARMS] },
  { id: 'ex-94', name: 'Cross-Body Extension', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-95', name: 'Band Pushdown', bodyPart: 'Triceps', category: 'Reps Only', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-96', name: 'Partial Tricep Extension', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },
  { id: 'ex-97', name: 'Isometric Tricep Squeeze', bodyPart: 'Triceps', category: 'Bodyweight', primaryMuscles: [MUSCLES.TRICEPS], secondaryMuscles: [] },

  // Legs (24)
  { id: 'ex-16', name: 'Leg Curl', bodyPart: 'Legs', category: 'Machine', primaryMuscles: [MUSCLES.HAMSTRINGS], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-17', name: 'Leg Extension', bodyPart: 'Legs', category: 'Machine', primaryMuscles: [MUSCLES.QUADS], secondaryMuscles: [] },
  { id: 'ex-9', name: 'Leg Press', bodyPart: 'Legs', category: 'Machine', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS, MUSCLES.CALVES] },
  { id: 'ex-2', name: 'Barbell Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS, MUSCLES.LOWER_BACK, MUSCLES.ADDUCTORS, MUSCLES.ABS] },
  { id: 'ex-98', name: 'Romanian Deadlift', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: [MUSCLES.HAMSTRINGS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.FOREARMS] },
  { id: 'ex-99', name: 'Dumbbell Walking Lunge', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS, MUSCLES.CALVES] },
  { id: 'ex-100', name: 'Bulgarian Split Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-101', name: 'Front Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: [MUSCLES.QUADS], secondaryMuscles: [MUSCLES.GLUTES, MUSCLES.LOWER_BACK, MUSCLES.ABS] },
  { id: 'ex-102', name: 'Hack Squat', bodyPart: 'Legs', category: 'Machine', primaryMuscles: [MUSCLES.QUADS], secondaryMuscles: [MUSCLES.GLUTES] },
  { id: 'ex-103', name: 'Dumbbell Step-Up', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-108', name: 'Sumo Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.ADDUCTORS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-109', name: 'Goblet Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.ABS, MUSCLES.TRAPS] },
  { id: 'ex-110', name: 'Pistol Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.CALVES, MUSCLES.ABS] },
  { id: 'ex-111', name: 'Wall Sit', bodyPart: 'Legs', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.QUADS], secondaryMuscles: [] },
  { id: 'ex-112', name: 'Sissy Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: [MUSCLES.QUADS], secondaryMuscles: [] },
  { id: 'ex-113', name: 'Jefferson Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES, MUSCLES.ADDUCTORS], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-114', name: 'Band Leg Curl', bodyPart: 'Legs', category: 'Reps Only', primaryMuscles: [MUSCLES.HAMSTRINGS], secondaryMuscles: [] },
  { id: 'ex-116', name: 'Box Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES, MUSCLES.CALVES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-150', name: 'Broad Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES, MUSCLES.HAMSTRINGS], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-151', name: 'Tuck Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: [MUSCLES.QUADS, MUSCLES.CALVES], secondaryMuscles: [MUSCLES.ABS] },
  { id: 'ex-152', name: 'Depth Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES, MUSCLES.CALVES], secondaryMuscles: [] },
  { id: 'ex-160', name: 'Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-161', name: 'Step-Up', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-162', name: 'Lunge', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },

  // Glutes (5)
  { id: 'ex-104', name: 'Glute Bridge', bodyPart: 'Glutes', category: 'Bodyweight', primaryMuscles: [MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-141', name: 'Barbell Hip Thrust', bodyPart: 'Glutes', category: 'Barbell', primaryMuscles: [MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-142', name: 'Glute Kickback', bodyPart: 'Glutes', category: 'Cable', primaryMuscles: [MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },
  { id: 'ex-143', name: 'Hip Abduction Machine', bodyPart: 'Glutes', category: 'Machine', primaryMuscles: [MUSCLES.GLUTES, MUSCLES.ABDUCTORS], secondaryMuscles: [] },
  { id: 'ex-144', name: 'Single-Leg Glute Bridge', bodyPart: 'Glutes', category: 'Bodyweight', primaryMuscles: [MUSCLES.GLUTES], secondaryMuscles: [MUSCLES.HAMSTRINGS] },

  // Calves (4)
  { id: 'ex-18', name: 'Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: [MUSCLES.GASTROCNEMIUS, MUSCLES.SOLEUS], secondaryMuscles: [] },
  { id: 'ex-105', name: 'Seated Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: [MUSCLES.SOLEUS], secondaryMuscles: [] },
  { id: 'ex-106', name: 'Donkey Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: [MUSCLES.GASTROCNEMIUS], secondaryMuscles: [] },
  { id: 'ex-107', name: 'Leg Press Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: [MUSCLES.GASTROCNEMIUS, MUSCLES.SOLEUS], secondaryMuscles: [] },

  // Core (16)
  { id: 'ex-20', name: 'Crunches', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.ABS], secondaryMuscles: [] },
  { id: 'ex-15', name: 'Plank', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.ABS, MUSCLES.TRANSVERSE_ABDOMINIS], secondaryMuscles: [MUSCLES.OBLIQUES, MUSCLES.FRONT_DELTS] },
  { id: 'ex-117', name: 'Russian Twist', bodyPart: 'Core', category: 'Dumbbell', primaryMuscles: [MUSCLES.OBLIQUES, MUSCLES.ABS], secondaryMuscles: [] },
  { id: 'ex-118', name: 'Leg Raise', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.ABS, MUSCLES.HIP_FLEXORS], secondaryMuscles: [] },
  { id: 'ex-119', name: 'Woodchopper', bodyPart: 'Core', category: 'Cable', primaryMuscles: [MUSCLES.OBLIQUES, MUSCLES.ABS], secondaryMuscles: [MUSCLES.FRONT_DELTS] },
  { id: 'ex-120', name: 'Pallof Press', bodyPart: 'Core', category: 'Cable', primaryMuscles: [MUSCLES.OBLIQUES, MUSCLES.TRANSVERSE_ABDOMINIS], secondaryMuscles: [MUSCLES.ABS] },
  { id: 'ex-121', name: 'Bird Dog', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.ABS], secondaryMuscles: [MUSCLES.GLUTES, MUSCLES.FRONT_DELTS] },
  { id: 'ex-122', name: 'Dead Bug', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.ABS, MUSCLES.TRANSVERSE_ABDOMINIS], secondaryMuscles: [] },
  { id: 'ex-123', name: 'Cable Crunch', bodyPart: 'Core', category: 'Cable', primaryMuscles: [MUSCLES.ABS], secondaryMuscles: [] },
  { id: 'ex-124', name: 'Ab Wheel Rollout', bodyPart: 'Core', category: 'Reps Only', primaryMuscles: [MUSCLES.ABS, MUSCLES.LATS], secondaryMuscles: [MUSCLES.TRANSVERSE_ABDOMINIS] },
  { id: 'ex-125', name: 'Flutter Kick', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.ABS, MUSCLES.HIP_FLEXORS], secondaryMuscles: [] },
  { id: 'ex-126', name: 'V-Up', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.ABS, MUSCLES.HIP_FLEXORS], secondaryMuscles: [] },
  { id: 'ex-127', name: 'Side Bend', bodyPart: 'Core', category: 'Dumbbell', primaryMuscles: [MUSCLES.OBLIQUES], secondaryMuscles: [] },
  { id: 'ex-128', name: 'Vacuum', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.TRANSVERSE_ABDOMINIS], secondaryMuscles: [] },
  { id: 'ex-156', name: 'Hanging Leg Raise', bodyPart: 'Core', category: 'Assisted Bodyweight', primaryMuscles: [MUSCLES.ABS, MUSCLES.HIP_FLEXORS], secondaryMuscles: [MUSCLES.FOREARMS, MUSCLES.LATS] },
  { id: 'ex-157', name: 'Side Plank', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.OBLIQUES], secondaryMuscles: [MUSCLES.ABS, MUSCLES.SIDE_DELTS] },
  { id: 'ex-159', name: 'Push-up and Rotation', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: [MUSCLES.OBLIQUES, MUSCLES.ABS], secondaryMuscles: [MUSCLES.PECTORALS, MUSCLES.FRONT_DELTS] },

  // Cardio (6)
  { id: 'ex-19', name: 'Running', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM], secondaryMuscles: [MUSCLES.QUADS, MUSCLES.HAMSTRINGS, MUSCLES.CALVES] },
  { id: 'ex-115', name: 'Cycling (Stationary)', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.QUADS], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-129', name: 'Jumping Jacks', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM], secondaryMuscles: [MUSCLES.CALVES, MUSCLES.SIDE_DELTS] },
  { id: 'ex-131', name: 'Mountain Climber', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.ABS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.HIP_FLEXORS] },
  { id: 'ex-135', name: 'Jump Rope', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.CALVES], secondaryMuscles: [] },
  { id: 'ex-136', name: 'Stair Climber', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.GLUTES, MUSCLES.QUADS], secondaryMuscles: [MUSCLES.CALVES] },
  { id: 'ex-158', name: 'High Knees', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.HIP_FLEXORS], secondaryMuscles: [MUSCLES.CALVES] },
  
  // Full Body (9)
  { id: 'ex-130', name: 'Burpee', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.PECTORALS, MUSCLES.QUADS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.ABS] },
  { id: 'ex-132', name: 'Rowing (Machine)', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.LATS], secondaryMuscles: [MUSCLES.QUADS, MUSCLES.HAMSTRINGS, MUSCLES.BICEPS] },
  { id: 'ex-133', name: 'Battle Rope', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.BICEPS, MUSCLES.TRICEPS, MUSCLES.ABS] },
  { id: 'ex-134', name: 'Kettlebell Swing', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: [MUSCLES.GLUTES, MUSCLES.HAMSTRINGS], secondaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.FRONT_DELTS, MUSCLES.FOREARMS] },
  { id: 'ex-137', name: 'Swimming', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM, MUSCLES.LATS], secondaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.QUADS] },
  { id: 'ex-145', name: 'Turkish Get-Up', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.ABS], secondaryMuscles: [MUSCLES.QUADS, MUSCLES.GLUTES, MUSCLES.TRICEPS] },
  { id: 'ex-146', name: 'Kettlebell Clean & Press', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: [MUSCLES.FRONT_DELTS, MUSCLES.GLUTES, MUSCLES.HAMSTRINGS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.TRAPS] },
  { id: 'ex-147', name: 'Kettlebell Snatch', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: [MUSCLES.GLUTES, MUSCLES.HAMSTRINGS, MUSCLES.FRONT_DELTS], secondaryMuscles: [MUSCLES.LOWER_BACK, MUSCLES.TRAPS] },
  { id: 'ex-149', name: 'Medicine Ball Slam', bodyPart: 'Full Body', category: 'Reps Only', primaryMuscles: [MUSCLES.LATS, MUSCLES.ABS], secondaryMuscles: [MUSCLES.TRICEPS, MUSCLES.FRONT_DELTS] },

  // Forearms (2)
  { id: 'ex-139', name: 'Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell', primaryMuscles: [MUSCLES.WRIST_FLEXORS], secondaryMuscles: [] },
  { id: 'ex-140', name: 'Reverse Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell', primaryMuscles: [MUSCLES.WRIST_EXTENSORS], secondaryMuscles: [] },

  // Mobility (4)
  { id: 'ex-138', name: 'Sun Salutation', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.CARDIOVASCULAR_SYSTEM], secondaryMuscles: [] },
  { id: 'ex-153', name: 'Foam Rolling', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: [], secondaryMuscles: [] },
  { id: 'ex-154', name: 'Hip Flexor Stretch', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.HIP_FLEXORS], secondaryMuscles: [] },
  { id: 'ex-155', name: 'Cat-Cow Stretch', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: [MUSCLES.LOWER_BACK], secondaryMuscles: [MUSCLES.ABS] },
];
