
import { Exercise } from '../types';

export const PREDEFINED_EXERCISES: Exercise[] = [
  // Chest (20)
  { id: 'ex-1', name: 'Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: ['Pectorals', 'Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-11', name: 'Dumbbell Fly', bodyPart: 'Chest', category: 'Dumbbell', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-12', name: 'Incline Dumbbell Press', bodyPart: 'Chest', category: 'Dumbbell', primaryMuscles: ['Upper Chest', 'Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-21', name: 'Cable Crossover', bodyPart: 'Chest', category: 'Cable', primaryMuscles: ['Pectorals', 'Lower Chest'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-22', name: 'Decline Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: ['Lower Chest', 'Pectorals'], secondaryMuscles: ['Triceps', 'Front Delts'] },
  { id: 'ex-23', name: 'Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: ['Pectorals', 'Front Delts'], secondaryMuscles: ['Triceps', 'Abs', 'Serratus Anterior'] },
  { id: 'ex-24', name: 'Dips', bodyPart: 'Chest', category: 'Assisted Bodyweight', primaryMuscles: ['Lower Chest', 'Triceps'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-25', name: 'Incline Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: ['Upper Chest', 'Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-26', name: 'Pec Deck Fly', bodyPart: 'Chest', category: 'Machine', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-27', name: 'Svend Press', bodyPart: 'Chest', category: 'Reps Only', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-28', name: 'Landmine Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: ['Upper Chest', 'Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-29', name: 'Deficit Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Triceps', 'Front Delts'] },
  { id: 'ex-30', name: 'Archer Push-Up', bodyPart: 'Chest', category: 'Bodyweight', primaryMuscles: ['Pectorals', 'Triceps'], secondaryMuscles: ['Front Delts', 'Abs'] },
  { id: 'ex-31', name: 'Machine Chest Press', bodyPart: 'Chest', category: 'Machine', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Triceps', 'Front Delts'] },
  { id: 'ex-32', name: 'Low-to-High Cable Fly', bodyPart: 'Chest', category: 'Cable', primaryMuscles: ['Upper Chest'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-33', name: 'High-to-Low Cable Fly', bodyPart: 'Chest', category: 'Cable', primaryMuscles: ['Lower Chest'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-34', name: 'Plate Press', bodyPart: 'Chest', category: 'Reps Only', primaryMuscles: ['Pectorals'], secondaryMuscles: ['Front Delts', 'Triceps'] },
  { id: 'ex-35', name: 'Suspension Push-Up', bodyPart: 'Chest', category: 'Assisted Bodyweight', primaryMuscles: ['Pectorals', 'Abs'], secondaryMuscles: ['Triceps', 'Front Delts', 'Serratus Anterior'] },
  { id: 'ex-36', name: 'Isometric Chest Squeeze', bodyPart: 'Chest', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Pectorals'], secondaryMuscles: [] },
  { id: 'ex-37', name: 'Speed Bench Press', bodyPart: 'Chest', category: 'Barbell', primaryMuscles: ['Pectorals', 'Triceps'], secondaryMuscles: ['Front Delts'] },
  
  // Back (23)
  { id: 'ex-5', name: 'Barbell Row', bodyPart: 'Back', category: 'Barbell', primaryMuscles: ['Lats', 'Rhomboids', 'Traps'], secondaryMuscles: ['Biceps', 'Rear Delts', 'Lower Back'] },
  { id: 'ex-10', name: 'Lat Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Lats'], secondaryMuscles: ['Biceps', 'Teres Major'] },
  { id: 'ex-3', name: 'Deadlift', bodyPart: 'Back', category: 'Barbell', primaryMuscles: ['Lower Back', 'Hamstrings', 'Glutes', 'Traps'], secondaryMuscles: ['Lats', 'Forearms', 'Quads'] },
  { id: 'ex-6', name: 'Pull Up', bodyPart: 'Back', category: 'Assisted Bodyweight', primaryMuscles: ['Lats', 'Teres Major'], secondaryMuscles: ['Biceps', 'Rhomboids', 'Traps'] },
  { id: 'ex-38', name: 'Seated Row', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Lats', 'Rhomboids', 'Traps'], secondaryMuscles: ['Biceps', 'Rear Delts'] },
  { id: 'ex-39', name: 'T-Bar Row', bodyPart: 'Back', category: 'Machine', primaryMuscles: ['Lats', 'Traps', 'Rhomboids'], secondaryMuscles: ['Biceps', 'Lower Back'] },
  { id: 'ex-40', name: 'Single-Arm Dumbbell Row', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: ['Lats'], secondaryMuscles: ['Biceps', 'Rhomboids'] },
  { id: 'ex-41', name: 'Face Pull', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Rear Delts', 'Rotator Cuff', 'Traps'], secondaryMuscles: ['Rhomboids'] },
  { id: 'ex-42', name: 'Inverted Row', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: ['Lats', 'Rhomboids'], secondaryMuscles: ['Biceps', 'Rear Delts', 'Abs'] },
  { id: 'ex-43', name: 'Rack Pull', bodyPart: 'Back', category: 'Barbell', primaryMuscles: ['Traps', 'Lower Back'], secondaryMuscles: ['Lats', 'Glutes', 'Hamstrings'] },
  { id: 'ex-44', name: 'Straight-Arm Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Lats', 'Teres Major'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-45', name: 'Hyperextension', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: ['Lower Back'], secondaryMuscles: ['Glutes', 'Hamstrings'] },
  { id: 'ex-46', name: 'Superman', bodyPart: 'Back', category: 'Bodyweight', primaryMuscles: ['Lower Back'], secondaryMuscles: ['Glutes'] },
  { id: 'ex-47', name: 'Renegade Row', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: ['Lats', 'Abs'], secondaryMuscles: ['Biceps', 'Front Delts', 'Obliques'] },
  { id: 'ex-48', name: 'Meadows Row', bodyPart: 'Back', category: 'Barbell', primaryMuscles: ['Lats', 'Rhomboids'], secondaryMuscles: ['Biceps', 'Forearms'] },
  { id: 'ex-49', name: 'Cable Pull-Over', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Lats'], secondaryMuscles: ['Triceps', 'Serratus Anterior'] },
  { id: 'ex-50', name: 'Chin-Up', bodyPart: 'Back', category: 'Assisted Bodyweight', primaryMuscles: ['Lats', 'Biceps'], secondaryMuscles: ['Rhomboids'] },
  { id: 'ex-51', name: 'Shrugs', bodyPart: 'Back', category: 'Dumbbell', primaryMuscles: ['Traps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-52', name: 'Reverse Grip Pulldown', bodyPart: 'Back', category: 'Cable', primaryMuscles: ['Lats', 'Biceps'], secondaryMuscles: ['Rhomboids'] },
  { id: 'ex-53', name: 'Band Pull-Apart', bodyPart: 'Back', category: 'Reps Only', primaryMuscles: ['Rear Delts', 'Rhomboids'], secondaryMuscles: ['Traps'] },
  { id: 'ex-54', name: 'Farmer\'s Carry', bodyPart: 'Back', category: 'Dumbbell', isTimed: true, primaryMuscles: ['Traps', 'Forearms'], secondaryMuscles: ['Abs', 'Obliques', 'Glutes'] },
  { id: 'ex-55', name: 'Good Morning', bodyPart: 'Back', category: 'Barbell', primaryMuscles: ['Lower Back', 'Hamstrings', 'Glutes'], secondaryMuscles: ['Abs'] },
  { id: 'ex-148', name: 'Kettlebell High Pull', bodyPart: 'Back', category: 'Kettlebell', primaryMuscles: ['Traps', 'Rear Delts'], secondaryMuscles: ['Lats', 'Biceps'] },

  // Shoulders (18)
  { id: 'ex-4', name: 'Overhead Press', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: ['Front Delts', 'Side Delts'], secondaryMuscles: ['Triceps', 'Upper Chest'] },
  { id: 'ex-56', name: 'Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Side Delts'], secondaryMuscles: ['Traps'] },
  { id: 'ex-57', name: 'Front Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Front Delts'], secondaryMuscles: [] },
  { id: 'ex-58', name: 'Rear Delt Fly', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Rear Delts'], secondaryMuscles: ['Rhomboids'] },
  { id: 'ex-59', name: 'Upright Row', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: ['Side Delts', 'Traps'], secondaryMuscles: ['Biceps', 'Front Delts'] },
  { id: 'ex-60', name: 'Arnold Press', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Front Delts', 'Side Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-61', name: 'Cable Lateral Raise', bodyPart: 'Shoulders', category: 'Cable', primaryMuscles: ['Side Delts'], secondaryMuscles: [] },
  { id: 'ex-62', name: 'Pike Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: ['Front Delts'], secondaryMuscles: ['Triceps', 'Upper Chest'] },
  { id: 'ex-63', name: 'Handstand Push-Up', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: ['Front Delts', 'Triceps'], secondaryMuscles: ['Side Delts'] },
  { id: 'ex-64', name: 'Egyptian Lateral Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Side Delts'], secondaryMuscles: [] },
  { id: 'ex-65', name: 'Y-Raise', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Side Delts', 'Traps'], secondaryMuscles: ['Rear Delts'] },
  { id: 'ex-66', name: 'Cuban Press', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Rotator Cuff', 'Side Delts'], secondaryMuscles: ['Traps'] },
  { id: 'ex-67', name: 'Machine Shoulder Press', bodyPart: 'Shoulders', category: 'Machine', primaryMuscles: ['Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-68', name: 'Behind-the-Neck Press', bodyPart: 'Shoulders', category: 'Barbell', primaryMuscles: ['Side Delts', 'Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-69', name: 'Plate Front Raise', bodyPart: 'Shoulders', category: 'Reps Only', primaryMuscles: ['Front Delts'], secondaryMuscles: [] },
  { id: 'ex-70', name: 'Band Shoulder Press', bodyPart: 'Shoulders', category: 'Reps Only', primaryMuscles: ['Front Delts'], secondaryMuscles: ['Triceps'] },
  { id: 'ex-71', name: 'Dumbbell Shrugs', bodyPart: 'Shoulders', category: 'Dumbbell', primaryMuscles: ['Traps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-72', name: 'Wall Slide', bodyPart: 'Shoulders', category: 'Bodyweight', primaryMuscles: ['Rotator Cuff', 'Serratus Anterior'], secondaryMuscles: ['Traps'] },

  // Biceps (14)
  { id: 'ex-7', name: 'Barbell Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-13', name: 'Bicep Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-73', name: 'Hammer Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: ['Brachialis', 'Forearms'], secondaryMuscles: ['Biceps', 'Forearms'] },
  { id: 'ex-74', name: 'Concentration Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-75', name: 'Preacher Curl', bodyPart: 'Biceps', category: 'Machine', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-76', name: 'Cable Curl', bodyPart: 'Biceps', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-77', name: 'Incline Dumbbell Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-78', name: '21s Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-79', name: 'Spider Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-80', name: 'Zottman Curl', bodyPart: 'Biceps', category: 'Dumbbell', primaryMuscles: ['Biceps', 'Forearms'], secondaryMuscles: ['Brachialis'] },
  { id: 'ex-81', name: 'Bayesian Cable Curl', bodyPart: 'Biceps', category: 'Cable', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-82', name: 'Isometric Bicep Hold', bodyPart: 'Biceps', category: 'Bodyweight', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-83', name: 'Band Curl', bodyPart: 'Biceps', category: 'Reps Only', primaryMuscles: ['Biceps'], secondaryMuscles: [] },
  { id: 'ex-84', name: 'Drag Curl', bodyPart: 'Biceps', category: 'Barbell', primaryMuscles: ['Biceps'], secondaryMuscles: ['Rear Delts'] },

  // Triceps (15)
  { id: 'ex-8', name: 'Skull Crusher', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-14', name: 'Tricep Extension', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-85', name: 'Tricep Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-86', name: 'Overhead Tricep Extension', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-87', name: 'Close-Grip Bench Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: ['Pectorals', 'Front Delts'] },
  { id: 'ex-88', name: 'French Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-89', name: 'Bench Dip', bodyPart: 'Triceps', category: 'Bodyweight', primaryMuscles: ['Triceps'], secondaryMuscles: ['Front Delts', 'Pectorals'] },
  { id: 'ex-90', name: 'Rope Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-91', name: 'JM Press', bodyPart: 'Triceps', category: 'Barbell', primaryMuscles: ['Triceps'], secondaryMuscles: ['Pectorals'] },
  { id: 'ex-92', name: 'Kickback', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-93', name: 'Reverse Grip Pushdown', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: ['Forearms'] },
  { id: 'ex-94', name: 'Cross-Body Extension', bodyPart: 'Triceps', category: 'Dumbbell', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-95', name: 'Band Pushdown', bodyPart: 'Triceps', category: 'Reps Only', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-96', name: 'Partial Tricep Extension', bodyPart: 'Triceps', category: 'Cable', primaryMuscles: ['Triceps'], secondaryMuscles: [] },
  { id: 'ex-97', name: 'Isometric Tricep Squeeze', bodyPart: 'Triceps', category: 'Bodyweight', primaryMuscles: ['Triceps'], secondaryMuscles: [] },

  // Legs (24)
  { id: 'ex-16', name: 'Leg Curl', bodyPart: 'Legs', category: 'Machine', primaryMuscles: ['Hamstrings'], secondaryMuscles: ['Calves'] },
  { id: 'ex-17', name: 'Leg Extension', bodyPart: 'Legs', category: 'Machine', primaryMuscles: ['Quads'], secondaryMuscles: [] },
  { id: 'ex-9', name: 'Leg Press', bodyPart: 'Legs', category: 'Machine', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Calves'] },
  { id: 'ex-2', name: 'Barbell Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Lower Back', 'Adductors', 'Abs'] },
  { id: 'ex-98', name: 'Romanian Deadlift', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: ['Hamstrings', 'Glutes'], secondaryMuscles: ['Lower Back', 'Forearms'] },
  { id: 'ex-99', name: 'Dumbbell Walking Lunge', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings', 'Calves'] },
  { id: 'ex-100', name: 'Bulgarian Split Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-101', name: 'Front Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes', 'Lower Back', 'Abs'] },
  { id: 'ex-102', name: 'Hack Squat', bodyPart: 'Legs', category: 'Machine', primaryMuscles: ['Quads'], secondaryMuscles: ['Glutes'] },
  { id: 'ex-103', name: 'Dumbbell Step-Up', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves'] },
  { id: 'ex-108', name: 'Sumo Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: ['Quads', 'Adductors', 'Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-109', name: 'Goblet Squat', bodyPart: 'Legs', category: 'Dumbbell', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Abs', 'Traps'] },
  { id: 'ex-110', name: 'Pistol Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves', 'Abs'] },
  { id: 'ex-111', name: 'Wall Sit', bodyPart: 'Legs', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Quads'], secondaryMuscles: [] },
  { id: 'ex-112', name: 'Sissy Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: ['Quads'], secondaryMuscles: [] },
  { id: 'ex-113', name: 'Jefferson Squat', bodyPart: 'Legs', category: 'Barbell', primaryMuscles: ['Quads', 'Glutes', 'Adductors'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-114', name: 'Band Leg Curl', bodyPart: 'Legs', category: 'Reps Only', primaryMuscles: ['Hamstrings'], secondaryMuscles: [] },
  { id: 'ex-116', name: 'Box Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: ['Quads', 'Glutes', 'Calves'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-150', name: 'Broad Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: ['Quads', 'Glutes', 'Hamstrings'], secondaryMuscles: ['Calves'] },
  { id: 'ex-151', name: 'Tuck Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: ['Quads', 'Calves'], secondaryMuscles: ['Abs'] },
  { id: 'ex-152', name: 'Depth Jump', bodyPart: 'Legs', category: 'Plyometrics', primaryMuscles: ['Quads', 'Glutes', 'Calves'], secondaryMuscles: [] },
  { id: 'ex-160', name: 'Squat', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-161', name: 'Step-Up', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Calves'] },
  { id: 'ex-162', name: 'Lunge', bodyPart: 'Legs', category: 'Bodyweight', primaryMuscles: ['Quads', 'Glutes'], secondaryMuscles: ['Hamstrings'] },

  // Glutes (5)
  { id: 'ex-104', name: 'Glute Bridge', bodyPart: 'Glutes', category: 'Bodyweight', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-141', name: 'Barbell Hip Thrust', bodyPart: 'Glutes', category: 'Barbell', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-142', name: 'Glute Kickback', bodyPart: 'Glutes', category: 'Cable', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'] },
  { id: 'ex-143', name: 'Hip Abduction Machine', bodyPart: 'Glutes', category: 'Machine', primaryMuscles: ['Glutes', 'Abductors'], secondaryMuscles: [] },
  { id: 'ex-144', name: 'Single-Leg Glute Bridge', bodyPart: 'Glutes', category: 'Bodyweight', primaryMuscles: ['Glutes'], secondaryMuscles: ['Hamstrings'] },

  // Calves (4)
  { id: 'ex-18', name: 'Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: ['Gastrocnemius', 'Soleus'], secondaryMuscles: [] },
  { id: 'ex-105', name: 'Seated Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: ['Soleus'], secondaryMuscles: [] },
  { id: 'ex-106', name: 'Donkey Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: ['Gastrocnemius'], secondaryMuscles: [] },
  { id: 'ex-107', name: 'Leg Press Calf Raise', bodyPart: 'Calves', category: 'Machine', primaryMuscles: ['Gastrocnemius', 'Soleus'], secondaryMuscles: [] },

  // Core (16)
  { id: 'ex-20', name: 'Crunches', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Abs'], secondaryMuscles: [] },
  { id: 'ex-15', name: 'Plank', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Abs', 'Transverse Abdominis'], secondaryMuscles: ['Obliques', 'Front Delts'] },
  { id: 'ex-117', name: 'Russian Twist', bodyPart: 'Core', category: 'Dumbbell', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: [] },
  { id: 'ex-118', name: 'Leg Raise', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Abs', 'Hip Flexors'], secondaryMuscles: [] },
  { id: 'ex-119', name: 'Woodchopper', bodyPart: 'Core', category: 'Cable', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: ['Front Delts'] },
  { id: 'ex-120', name: 'Pallof Press', bodyPart: 'Core', category: 'Cable', primaryMuscles: ['Obliques', 'Transverse Abdominis'], secondaryMuscles: ['Abs'] },
  { id: 'ex-121', name: 'Bird Dog', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Lower Back', 'Abs'], secondaryMuscles: ['Glutes', 'Front Delts'] },
  { id: 'ex-122', name: 'Dead Bug', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Abs', 'Transverse Abdominis'], secondaryMuscles: [] },
  { id: 'ex-123', name: 'Cable Crunch', bodyPart: 'Core', category: 'Cable', primaryMuscles: ['Abs'], secondaryMuscles: [] },
  { id: 'ex-124', name: 'Ab Wheel Rollout', bodyPart: 'Core', category: 'Reps Only', primaryMuscles: ['Abs', 'Lats'], secondaryMuscles: ['Transverse Abdominis'] },
  { id: 'ex-125', name: 'Flutter Kick', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Abs', 'Hip Flexors'], secondaryMuscles: [] },
  { id: 'ex-126', name: 'V-Up', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Abs', 'Hip Flexors'], secondaryMuscles: [] },
  { id: 'ex-127', name: 'Side Bend', bodyPart: 'Core', category: 'Dumbbell', primaryMuscles: ['Obliques'], secondaryMuscles: [] },
  { id: 'ex-128', name: 'Vacuum', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Transverse Abdominis'], secondaryMuscles: [] },
  { id: 'ex-156', name: 'Hanging Leg Raise', bodyPart: 'Core', category: 'Assisted Bodyweight', primaryMuscles: ['Abs', 'Hip Flexors'], secondaryMuscles: ['Forearms', 'Lats'] },
  { id: 'ex-157', name: 'Side Plank', bodyPart: 'Core', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Obliques'], secondaryMuscles: ['Abs', 'Side Delts'] },
  { id: 'ex-159', name: 'Push-up and Rotation', bodyPart: 'Core', category: 'Bodyweight', primaryMuscles: ['Obliques', 'Abs'], secondaryMuscles: ['Pectorals', 'Front Delts'] },

  // Cardio (6)
  { id: 'ex-19', name: 'Running', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System'], secondaryMuscles: ['Quads', 'Hamstrings', 'Calves'] },
  { id: 'ex-115', name: 'Cycling (Stationary)', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Quads'], secondaryMuscles: ['Calves'] },
  { id: 'ex-129', name: 'Jumping Jacks', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System'], secondaryMuscles: ['Calves', 'Side Delts'] },
  { id: 'ex-131', name: 'Mountain Climber', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Abs'], secondaryMuscles: ['Front Delts', 'Hip Flexors'] },
  { id: 'ex-135', name: 'Jump Rope', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Calves'], secondaryMuscles: [] },
  { id: 'ex-136', name: 'Stair Climber', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Glutes', 'Quads'], secondaryMuscles: ['Calves'] },
  { id: 'ex-158', name: 'High Knees', bodyPart: 'Cardio', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Hip Flexors'], secondaryMuscles: ['Calves'] },
  
  // Full Body (9)
  { id: 'ex-130', name: 'Burpee', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Pectorals', 'Quads'], secondaryMuscles: ['Front Delts', 'Abs'] },
  { id: 'ex-132', name: 'Rowing (Machine)', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Lats'], secondaryMuscles: ['Quads', 'Hamstrings', 'Biceps'] },
  { id: 'ex-133', name: 'Battle Rope', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Front Delts'], secondaryMuscles: ['Biceps', 'Triceps', 'Abs'] },
  { id: 'ex-134', name: 'Kettlebell Swing', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: ['Glutes', 'Hamstrings'], secondaryMuscles: ['Lower Back', 'Front Delts', 'Forearms'] },
  { id: 'ex-137', name: 'Swimming', bodyPart: 'Full Body', category: 'Cardio', isTimed: true, primaryMuscles: ['Cardiovascular System', 'Lats'], secondaryMuscles: ['Front Delts', 'Quads'] },
  { id: 'ex-145', name: 'Turkish Get-Up', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: ['Front Delts', 'Abs'], secondaryMuscles: ['Quads', 'Glutes', 'Triceps'] },
  { id: 'ex-146', name: 'Kettlebell Clean & Press', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: ['Front Delts', 'Glutes', 'Hamstrings'], secondaryMuscles: ['Triceps', 'Traps'] },
  { id: 'ex-147', name: 'Kettlebell Snatch', bodyPart: 'Full Body', category: 'Kettlebell', primaryMuscles: ['Glutes', 'Hamstrings', 'Front Delts'], secondaryMuscles: ['Lower Back', 'Traps'] },
  { id: 'ex-149', name: 'Medicine Ball Slam', bodyPart: 'Full Body', category: 'Reps Only', primaryMuscles: ['Lats', 'Abs'], secondaryMuscles: ['Triceps', 'Front Delts'] },

  // Forearms (2)
  { id: 'ex-139', name: 'Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell', primaryMuscles: ['Wrist Flexors'], secondaryMuscles: [] },
  { id: 'ex-140', name: 'Reverse Wrist Curl', bodyPart: 'Forearms', category: 'Dumbbell', primaryMuscles: ['Wrist Extensors'], secondaryMuscles: [] },

  // Mobility (4)
  { id: 'ex-138', name: 'Sun Salutation', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Cardiovascular System'], secondaryMuscles: [] },
  { id: 'ex-153', name: 'Foam Rolling', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: [], secondaryMuscles: [] },
  { id: 'ex-154', name: 'Hip Flexor Stretch', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Hip Flexors'], secondaryMuscles: [] },
  { id: 'ex-155', name: 'Cat-Cow Stretch', bodyPart: 'Mobility', category: 'Bodyweight', isTimed: true, primaryMuscles: ['Lower Back'], secondaryMuscles: ['Abs'] },
];
